services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: anastasiyaguryanova/time-backend:latest
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: anastasiyaguryanova/time-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
